config/routes.rb
Rails.application.routes.draw do
  resources :mottos
  resources :xz do
    collection do
      get 'detail'
      get 'api'
    end
  end
  
  get 'ls' =>"ls#index"  
  root "mottos#show"

end

app/models/motto.rb
class Motto < ActiveRecord::Base
end

app/models/xz.rb
class Xz < ActiveRecord::Base
  
  def self.all_names
     @@all_names
  end
  
  @@all_names=[
        "aries",
        "taurus",
        "gemini",
        "cancer",
        "leo",
        "virgo",
        "libra",
        "scorpio",
        "sagittarius",
        "capricorn",
        "aquarius",
        "pisces"]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/ls_controller.rb
class LsController < ApplicationController
  def index
    
  end
end

app/controllers/mottos_controller.rb
class MottosController < ApplicationController
  before_action :set_motto, only: [:edit, :update, :destroy]

  # GET /mottos
  # GET /mottos.json
  def index
    @mottos = Motto.all
  end

  # GET /mottos/1
  # GET /mottos/1.json
  def show
    @motto = Motto.find_by_id(params[:id])
    if @motto
      @date = @motto.downloaded_at.to_date
    else
      redirect_to motto_path(Motto.last)
    end
  end

  # GET /mottos/new
  def new
    @motto = Motto.new
  end

  # GET /mottos/1/edit
  def edit
  end

  # POST /mottos
  # POST /mottos.json
  def create
    @motto = Motto.new(motto_params)

    respond_to do |format|
      if @motto.save
        format.html { redirect_to @motto, notice: 'Motto was successfully created.' }
        format.json { render :show, status: :created, location: @motto }
      else
        format.html { render :new }
        format.json { render json: @motto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mottos/1
  # PATCH/PUT /mottos/1.json
  def update
    respond_to do |format|
      if @motto.update(motto_params)
        format.html { redirect_to @motto, notice: 'Motto was successfully updated.' }
        format.json { render :show, status: :ok, location: @motto }
      else
        format.html { render :edit }
        format.json { render json: @motto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mottos/1
  # DELETE /mottos/1.json
  def destroy
    @motto.destroy
    respond_to do |format|
      format.html { redirect_to mottos_url, notice: 'Motto was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_motto
      @motto = Motto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def motto_params
      params.require(:motto).permit(:content, :downloaded_at, :remote_image_url)
    end
end

app/controllers/xz_controller.rb
require 'open-uri'
require 'net/http'
class XzController < ApplicationController
  def index
  end
  
  def api
    date = DateTime.now.strftime("%Y-%m-%d")
    @name = name = params[:name]
    xz = Xz.find_by_downloaded_at_and_name(date,name)
    if not xz
      html_response = nil
      open("http://c.51wnl.com/API/GetConstellationV2.ashx?starname=#{name}") do |http|  
         html_response = http.read  
      end
      json = JSON.parse(html_response)
      date = json["Date"]
      if date
        xz = Xz.new 
        xz.downloaded_at = date
        xz.name = name
        xz.innfo = html_response
        xz.save if not Xz.find_by_downloaded_at_and_name(date,name)
      end
    end
    
    render :text=>xz.innfo
    
  end
  
  def detail
    @name = params[:name]
    
    @id = Xz.all_names.index(@name).to_i+1
    if @id<10
      @id = "0#{@id}"
    else
      @id = "#{@id}"
    end
  end
  

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ls_helper.rb
module LsHelper
end

app/helpers/mottos_helper.rb
module MottosHelper
end

app/helpers/xz_helper.rb
module XzHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="description" content="">
    <meta name="HandheldFriendly" content="True">
    <meta name="MobileOptimized" content="320">
    <meta name="viewport" content="width=device-width, user-scalable = no,initial-scale=1.0, maximum-scale=1.0, user-scalable=no"/>
	
    <meta http-equiv="cleartype" content="on">
	
    <meta name = "format-detection" content = "telephone=no">
	
    <title><%= content_for?(:title) ? yield(:title) : "每日一言" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>
	  <%=yield%> 
  </body>
</html>

app/views/ls/index.html.erb
<%= content_for :title do%>
今日历史
<%end%>
 
<link rel="stylesheet" href="/css/ls.css">
<script type="text/javascript" src="/js/zepto.js"></script>
<script type="text/javascript" src="/js/ls.js"></script>
<div id="main_m">
     <header>
         <a id="todayBtn" class="today" href="javascript:void(0)">今天</a>
         <span>今日历史</span>
         <a id="closeBtn"  class="close" href="javascript:void(0)"></a>
     </header>
     <div class="content">
         <div class="topSelectContent">
             <div class="dayInfo">
                 <div class="preve">
                     <a id="preveBtn" href="javascript:void(0)"></a>
                 </div>
                 <div class="day">
                     <span class="dayShow"></span>
                     <span class="dayCount"></span>
                 </div>
                 <div class="next">
                     <a id="nextBtn" href="javascript:void(0)"></a>
                 </div>
             </div>
         </div>
         <div class="tempList">
             <ul>
                 <li class="item hidden">
                     <span class="year"></span>
                     <span class="title"></span>
                 </li>
             </ul>
         </div>
         <div class="contentList">
             <ul>
             </ul>
         </div>
     </div>
 </div>
 <div class="mask hidden"></div>
 <a class="shareLink hidden" href="javascript:void(0)"><span class="clickContent"></span></a>
 

app/views/mottos/_form.html.erb
<%= form_for(@motto) do |f| %>
  <% if @motto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@motto.errors.count, "error") %> prohibited this motto from being saved:</h2>

      <ul>
      <% @motto.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_field :content %>
  </div>
  <div class="field">
    <%= f.label :downloaded_at %><br>
    <%= f.text_field :downloaded_at %>
  </div>
  <div class="field">
    <%= f.label :remote_image_url %><br>
    <%= f.text_field :remote_image_url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/mottos/edit.html.erb
<h1>Editing Motto</h1>

<%= render 'form' %>

<%= link_to 'Show', @motto %> |
<%= link_to 'Back', mottos_path %>

app/views/mottos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Mottos</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>Downloaded at</th>
      <th>Remote image url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @mottos.each do |motto| %>
      <tr>
        <td><%= motto.content %></td>
        <td><%= motto.downloaded_at %></td>
        <td><%= motto.remote_image_url %></td>
        <td><%= link_to 'Show', motto %></td>
        <td><%= link_to 'Edit', edit_motto_path(motto) %></td>
        <td><%= link_to 'Destroy', motto, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Motto', new_motto_path %>

app/views/mottos/new.html.erb
<h1>New Motto</h1>

<%= render 'form' %>

<%= link_to 'Back', mottos_path %>

app/views/mottos/show.html.erb
    <%= content_for :title do%>
		每日一言-<%=@motto.content%>
	<%end%>
    <link rel="stylesheet" href="/css/mryy.css"/>
    <script type="text/javascript" src="http://res.wx.qq.com/open/js/jweixin-1.0.0.js"></script>
    <script src="/js/jquery-fastclick.min.js" type="text/javascript"></script>
</head>
<body>
	<!-- <div class="topBanner">
		<div class="bannerContent">
	        <div class="imgContent">
	            <img class="userImg" src="/img/icon.png">
	        </div>
	        <div class="userInfoContent">
	            <div class="tableWrapper">
	                <div class="username"></div>
	                <div class="shareDate">定制广告位招租，微信：@stormchaser</div>
	            </div>
	        </div>
	    </div>
	</div> -->
    <div class="main">
        <div class="mainContent">
            <div class="imgWrapper">
                <img class="contentImg" src="<%=@motto.remote_image_url%>" alt="每日一言图片"/>
                <div class="contentWrapper">
                    <div class="txtContent">
                        <div class="dayInfo">
                            <div class="dayNumber"><%= @date.day%></div>
                            <div class="dayOther">
                                <div class="monthNum"><%= @date.strftime("%B")%></div>
                                <div class="weekNum"><%= @date.strftime("%A")%></div>
                            </div>
                        </div>
                        <div class="yyTxt"><%=@motto.content%></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
	
<footer>
  <script type="text/javascript">
      /*banner*/
      var cpro_id = "u2169275";
  </script>
  <script src="http://cpro.baidustatic.com/cpro/ui/cm.js" type="text/javascript"></script>
  <script>
  	var window_height = parseInt($(window).height());
  	var img_height = parseInt($('.contentImg').css("height"));
  	var top_bar_height = 0;
  	var margin_top = img_height-(window_height-top_bar_height);
  	if(margin_top>0){
  		$('.contentImg').css('margin-top',''+(-margin_top)+'px');
  	}
  </script>
</footer>	
	
</html>

app/views/xz/detail.html.erb
 <%= content_for :title do%>
	每日星座-<%=@name%>
 <%end%>
 <link rel="stylesheet" href="/css/xz.css"/>
 
<div class="main">
    <div class="mainContent">
        <div class="xzOperate">
            <div class="xzImg contentImg"><%=image_tag "/img/star#{@id}@3x.png",:width=>"100%"%></div>
            <div class="xzName1"></div>
            <a class="indexLink" href="/xz">查看我的星座</a>
        </div>
        <div class="briefDetailContent">
            <div class="leftContent">
                <div class="detailLine">
                    <div class="lineTitle">综合运势</div>
                    <div class="lineDesc zongheNum">
                        <div class="star"></div>
                        <div class="star"></div>
                        <div class="star"></div>
                        <div class="star"></div>
                        <div class="star"></div>
                    </div>
                </div>
                <div class="detailLine">
                    <div class="lineTitle">事业运势</div>
                    <div class="lineDesc shiyeNum">
                        <div class="star"></div>
                        <div class="star"></div>
                        <div class="star"></div>
                        <div class="star"></div>
                        <div class="star"></div>
                    </div>
                </div>
                <div class="detailLine">
                    <div class="lineTitle">健康指数</div>
                    <div class="lineDesc jiankangNum"></div>
                </div>
                <div class="detailLine">
                    <div class="lineTitle">幸运颜色</div>
                    <div class="lineDesc yanse"></div>
                </div>
                <div class="detailLine">
                    <div class="lineTitle">适配星座</div>
                    <div class="lineDesc shipei"></div>
                </div>
            </div>
            <div class="rightContent">
                <div class="detailLine">
                    <div class="lineTitle">爱情运势</div>
                    <div class="lineDesc aiqingNum">
                        <div class="star"></div>
                        <div class="star"></div>
                        <div class="star"></div>
                        <div class="star"></div>
                        <div class="star"></div>
                    </div>
                </div>
                <div class="detailLine">
                    <div class="lineTitle">财富运势</div>
                    <div class="lineDesc caifuNum">
                        <div class="star"></div>
                        <div class="star"></div>
                        <div class="star"></div>
                        <div class="star"></div>
                        <div class="star"></div>
                    </div>
                </div>
                <div class="detailLine">
                    <div class="lineTitle">商谈指数</div>
                    <div class="lineDesc shangtanNum"></div>
                </div>
                <div class="detailLine">
                    <div class="lineTitle">幸运数字</div>
                    <div class="lineDesc shuzi"></div>
                </div>
            </div>
        </div>
        <div class="descriptionContent">
            <div class="titleContent">
                <div class="title">整体运势</div>
                <div class="lineDom"></div>
            </div>
            <div class="descriptionTxt zhengti"></div>
            <div class="titleContent">
                <div class="title">爱情运势</div>
                <div class="lineDom"></div>
            </div>
            <div class="descriptionTxt aiqing"></div>
            <div class="titleContent">
                <div class="title">事业运势</div>
                <div class="lineDom"></div>
            </div>
            <div class="descriptionTxt shiye"></div>
            <div class="titleContent">
                <div class="title">财富运势</div>
                <div class="lineDom"></div>
            </div>
            <div class="descriptionTxt caifu"></div>
            <div class="titleContent">
                <div class="title">健康运势</div>
                <div class="lineDom"></div>
            </div>
            <div class="descriptionTxt jiankang"></div>
        </div>
    </div>
</div>
<script type="text/javascript" src="/js/jquery-fastclick.min.js"></script>
 <%=javascript_include_tag "/js/xz.js"%>
<footer>
  <script type="text/javascript">
      /*banner*/
      var cpro_id = "u2169275";
  </script>
  <script src="http://cpro.baidustatic.com/cpro/ui/cm.js" type="text/javascript"></script>
</footer>

app/views/xz/index.html.erb
 <%= content_for :title do%>
	每日星座
 <%end%>
 <link rel="stylesheet" href="/css/xz.css"/>
 
 <div class="main">
        <div class="mainContent">
            <div class="listContent">
                <a href="/xz/detail?name=aries&id=01" data-id="1" class="no1">
                    <div class="xzIndexImg"></div>
                    <div class="xzName">白羊座</div>
                </a>
                <a href="/xz/detail?name=taurus&id=02" data-id="2" class="no2">
                    <div class="xzIndexImg"></div>
                    <div class="xzName">金牛座</div>
                </a>
                <a href="/xz/detail?name=gemini&id=03" data-id="3" class="no3">
                    <div class="xzIndexImg"></div>
                    <div class="xzName">双子座</div>
                </a>
                <a href="/xz/detail?name=cancer&id=04" data-id="4" class="no4">
                    <div class="xzIndexImg"></div>
                    <div class="xzName">巨蟹座</div>
                </a>
                <a href="/xz/detail?name=leo&id=05" data-id="5" class="no5">
                    <div class="xzIndexImg"></div>
                    <div class="xzName">狮子座</div>
                </a>
                <a href="/xz/detail?name=virgo&id=06" data-id="6" class="no6">
                    <div class="xzIndexImg"></div>
                    <div class="xzName">处女座</div>
                </a>
                <a href="/xz/detail?name=libra&id=07" data-id="7" class="no7">
                    <div class="xzIndexImg"></div>
                    <div class="xzName">天秤座</div>
                </a>
                <a href="/xz/detail?name=scorpio&id=08" data-id="8" class="no8">
                    <div class="xzIndexImg"></div>
                    <div class="xzName">天蝎座</div>
                </a>
                <a href="/xz/detail?name=sagittarius&id=09" data-id="9" class="no9">
                    <div class="xzIndexImg"></div>
                    <div class="xzName">射手座</div>
                </a>
                <a href="/xz/detail?name=capricorn&id=10" data-id="10" class="no10">
                    <div class="xzIndexImg"></div>
                    <div class="xzName">魔蝎座</div>
                </a>
                <a href="/xz/detail?name=aquarius&id=11" data-id="11" class="no11">
                    <div class="xzIndexImg"></div>
                    <div class="xzName">水瓶座</div>
                </a>
                <a href="/xz/detail?name=pisces&id=12" data-id="12" class="no12">
                    <div class="xzIndexImg"></div>
                    <div class="xzName">双鱼座</div>
                </a>
            </div>
        </div>
      
    </div>
    <script type="text/javascript" src="js/jquery-fastclick.min.js"></script>
    <script type="text/javascript" src="js/index.js"></script>
	
	<footer>
	  <script type="text/javascript">
	      /*banner*/
	      var cpro_id = "u2169275";
	  </script>
	  <script src="http://cpro.baidustatic.com/cpro/ui/cm.js" type="text/javascript"></script>
	</footer>
</body>